version: "3.9"

services:
  web:
    build:
      context: .
      target: prod
    container_name: lumix
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
